from __future__ import annotations
import tudatpy.kernel.dynamics.environment_setup.radiation_pressure
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import BodyPanelReflectionLawSettings
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import CannonBallRadiationPressureInterfaceSettings
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import KnockeTypeSurfacePropertyDistributionModel
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import LuminosityModelSettings
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import PanelRadiosityModelSettings
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import RadiationPressureInterfaceSettings
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import RadiationPressureTargetModelSettings
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import RadiationPressureTargetModelType
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import RadiationPressureType
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import RadiationSourceModelSettings
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import SphericalHarmonicsSurfacePropertyDistributionModel
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import SurfacePropertyDistributionSettings
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import cannonball
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import cannonball_radiation_target
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import constant_albedo_surface_radiosity
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import constant_luminosity
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import constant_radiosity
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import constant_surface_property_distribution
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import custom_surface_property_distribution
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import irradiance_based_constant_luminosity
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import irradiance_based_time_variable_luminosity
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import isotropic_radiation_source
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import knocke_type_surface_property_distribution
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import lambertian_body_panel_reflection
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import panelled_extended_radiation_source
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import panelled_radiation_target
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import predefined_knocke_type_surface_property_distribution
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import predefined_spherical_harmonic_surface_property_distribution
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import specular_diffuse_body_panel_reflection
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import spherical_harmonic_surface_property_distribution
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import thermal_emission_angle_based_radiosity
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import thermal_emission_blackbody_constant_emissivity
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import thermal_emission_blackbody_variable_emissivity
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import time_variable_luminosity
from tudatpy.kernel.dynamics.environment_setup.radiation_pressure import variable_albedo_surface_radiosity
__all__: list[str] = ['BodyPanelReflectionLawSettings', 'CannonBallRadiationPressureInterfaceSettings', 'KnockeTypeSurfacePropertyDistributionModel', 'LuminosityModelSettings', 'PanelRadiosityModelSettings', 'RadiationPressureInterfaceSettings', 'RadiationPressureTargetModelSettings', 'RadiationPressureTargetModelType', 'RadiationPressureType', 'RadiationSourceModelSettings', 'SphericalHarmonicsSurfacePropertyDistributionModel', 'SurfacePropertyDistributionSettings', 'albedo_dlam1', 'albedo_knocke', 'cannonball', 'cannonball_radiation_pressure_interface', 'cannonball_radiation_target', 'cannonball_target', 'constant_albedo_surface_radiosity', 'constant_luminosity', 'constant_radiosity', 'constant_surface_property_distribution', 'custom', 'custom_surface_property_distribution', 'emissivity_knocke', 'irradiance_based_constant_luminosity', 'irradiance_based_time_variable_luminosity', 'isotropic_radiation_source', 'knocke_type_surface_property_distribution', 'lambertian_body_panel_reflection', 'multi_type_target', 'paneled_target', 'panelled_extended_radiation_source', 'panelled_radiation_target', 'predefined_knocke_type_surface_property_distribution', 'predefined_spherical_harmonic_surface_property_distribution', 'specular_diffuse_body_panel_reflection', 'spherical_harmonic_surface_property_distribution', 'thermal_emission_angle_based_radiosity', 'thermal_emission_blackbody_constant_emissivity', 'thermal_emission_blackbody_variable_emissivity', 'time_variable_luminosity', 'undefined_target', 'variable_albedo_surface_radiosity']
albedo_dlam1: tudatpy.kernel.dynamics.environment_setup.radiation_pressure.SphericalHarmonicsSurfacePropertyDistributionModel  # value = <SphericalHarmonicsSurfacePropertyDistributionModel.albedo_dlam1: 1>
albedo_knocke: tudatpy.kernel.dynamics.environment_setup.radiation_pressure.KnockeTypeSurfacePropertyDistributionModel  # value = <KnockeTypeSurfacePropertyDistributionModel.albedo_knocke: 1>
cannonball_radiation_pressure_interface: tudatpy.kernel.dynamics.environment_setup.radiation_pressure.RadiationPressureType  # value = <RadiationPressureType.cannonball_radiation_pressure_interface: 0>
cannonball_target: tudatpy.kernel.dynamics.environment_setup.radiation_pressure.RadiationPressureTargetModelType  # value = <RadiationPressureTargetModelType.cannonball_target: 0>
custom: tudatpy.kernel.dynamics.environment_setup.radiation_pressure.KnockeTypeSurfacePropertyDistributionModel  # value = <KnockeTypeSurfacePropertyDistributionModel.custom: 0>
emissivity_knocke: tudatpy.kernel.dynamics.environment_setup.radiation_pressure.KnockeTypeSurfacePropertyDistributionModel  # value = <KnockeTypeSurfacePropertyDistributionModel.emissivity_knocke: 2>
multi_type_target: tudatpy.kernel.dynamics.environment_setup.radiation_pressure.RadiationPressureTargetModelType  # value = <RadiationPressureTargetModelType.multi_type_target: 2>
paneled_target: tudatpy.kernel.dynamics.environment_setup.radiation_pressure.RadiationPressureTargetModelType  # value = <RadiationPressureTargetModelType.paneled_target: 1>
undefined_target: tudatpy.kernel.dynamics.environment_setup.radiation_pressure.RadiationPressureTargetModelType  # value = <RadiationPressureTargetModelType.undefined_target: 3>
